# Project: chess
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Plateau.o
LINKOBJ  = main.o Plateau.o
LIBS     = -L"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/include" -I"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/include" -I"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Study/1ere annee/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = chess.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = D:\Study\1ere annee\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Plateau.o: Plateau.cpp
	$(CPP) -c Plateau.cpp -o Plateau.o $(CXXFLAGS)
